### ISSUE TITLE
It's clean and good code!

### ISSUE THREAD

**Issue by YoonSeongKyeong** [sha-pizza/JAVApractice#2]
your code shows class hierarchy well with A, B, C level notation.
I'm impressed!
I want to learn your coding style and make my code clean too
Thank you for making good code :)

**Comment by sha-pizza** [comment]
감사합니다! 저 나름의 방식으로 클래스 위계에 따라 정리해 두었는데, 다른 분들께서도 잘 이해가 되는 방식이라니 다행인 것 같습니다!
